import { FormEvent, useEffect, useState } from 'react';
import {
  ArrowDown,
  ArrowRight,
  AudioLines,
  BarChart3,
  Check,
  ChevronDown,
  Circle,
  FileText,
  Headphones,
  Menu,
  Mic,
  Play,
  Search,
  ShieldCheck,
  Square,
  Target,
  X,
} from 'lucide-react';
import './index.css';

type Route = '/' | '/login' | '/register';

function App() {
  const [route, setRoute] = useState<Route>((window.location.pathname as Route) || '/');
  const goTo = (next: Route) => { window.history.pushState({}, '', next); setRoute(next); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  useEffect(() => { const onPop = () => setRoute((window.location.pathname as Route) || '/'); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop); }, []);
  if (route === '/login') return <AuthPage type="login" goTo={goTo} />;
  if (route === '/register') return <AuthPage type="register" goTo={goTo} />;
  return <LandingPage goTo={goTo} />;
}

function Logo() { return <span className="public-logo"><span className="logo-mark"><i /><i /><i /></span><span>MeetMind</span></span>; }
function scrollToSection(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function Header({ goTo }: { goTo: (route: Route) => void }) { const [open, setOpen] = useState(false); const link = (id: string) => { setOpen(false); scrollToSection(id); }; return <header className="site-header"><div className="nav-inner"><button className="logo-button" onClick={() => { setOpen(false); scrollToSection('top'); }}><Logo /></button><nav className={`site-nav ${open ? 'nav-open' : ''}`}><button onClick={() => link('product')}>Product</button><button onClick={() => link('workflow')}>How it works</button><button onClick={() => link('features')}>Features</button><button onClick={() => link('about')}>About us</button><button onClick={() => link('contact')}>Contact</button><span className="nav-divider" /><button onClick={() => goTo('/login')}>Sign in</button><button className="nav-cta" onClick={() => goTo('/register')}>Get started</button></nav><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X size={18} /> : <Menu size={18} />}</button></div></header>; }

function LandingPage({ goTo }: { goTo: (route: Route) => void }) { return <div className="public-site" id="top"><Header goTo={goTo} /><main><Hero goTo={goTo} /><ProductPreview /><Intro /><Workflow /><AudioFeature /><Intelligence /><HumanVerification /><TasksPreview /><AnalyticsPreview /><Privacy /><About /><Contact /><FinalCta goTo={goTo} /></main><Footer goTo={goTo} /></div>; }
function Hero({ goTo }: { goTo: (route: Route) => void }) { return <section className="hero section-frame"><div className="hero-content"><div className="overline"><span className="overline-line" />AI-POWERED MEETING ASSISTANT</div><h1>Turn meetings into<br /><em>work that gets done.</em></h1><p>MeetMind captures your meetings, creates structured summaries, identifies decisions and turns verified action items into trackable tasks.</p><div className="hero-actions"><button className="primary-button" onClick={() => goTo('/register')}>Get started <ArrowRight size={15} /></button><button className="quiet-button" onClick={() => scrollToSection('workflow')}>See how it works <ArrowDown size={14} /></button></div><div className="trust-line"><span><Check size={13} /> Human-reviewed AI</span><span><ShieldCheck size={13} /> Privacy-aware processing</span></div></div><div className="hero-footnote"><span>Built for the moments after the call.</span><span className="hero-scroll">Scroll to explore <ArrowDown size={13} /></span></div></section>; }

function ProductPreview() { return <section className="preview-section section-frame" id="product"><div className="preview-window"><div className="preview-chrome"><div className="window-dots"><i /><i /><i /></div><span>MeetMind / live meeting</span><span className="preview-live"><i /> Recording · 24:32</span></div><div className="preview-body"><aside className="preview-sidebar"><Logo /><div className="preview-nav"><span className="selected"><Circle size={7} fill="currentColor" />Home</span><span><Headphones size={13} />Meetings</span><span><Target size={13} />Tasks</span><span><BarChart3 size={13} />Analytics</span></div><span className="preview-new"><span>+</span> New meeting</span><div className="preview-workspace"><small>WORKSPACE</small><span><FileText size={13} />Recent meetings</span><span><Target size={13} />Starred</span></div><div className="preview-settings"><span>Settings</span><span className="preview-user">R</span></div></aside><div className="preview-main"><div className="preview-main-header"><div><small>LIVE MEETING</small><h3>Project Planning Meeting</h3><p>Started 10:30 AM · Two independent audio sources</p></div><button className="preview-stop"><Square size={10} fill="currentColor" />Stop recording</button></div><div className="preview-source-label">AUDIO SOURCES</div><div className="preview-sources"><PreviewSource icon={<Headphones size={15} />} title="Meeting audio" detail="Chrome · Meeting Tab" /><PreviewSource icon={<Mic size={15} />} title="Microphone" detail="Default Microphone" /></div><div className="preview-transcript-head"><span>LIVE TRANSCRIPT</span><Search size={13} /></div><div className="preview-transcript"><PreviewLine time="10:42:08" source="MEETING">We need to complete the frontend before Friday.</PreviewLine><PreviewLine time="10:42:15" source="YOU">I'll finish the dashboard and recording interface first.</PreviewLine><PreviewLine time="10:42:23" source="MEETING">Great. We'll review everything Monday.</PreviewLine></div></div></div></div><div className="preview-caption"><span>MeetMind keeps the conversation visible while you stay in it.</span><span>PRODUCT PREVIEW / 01</span></div></section>; }
function PreviewSource({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="preview-source"><span className="source-glyph">{icon}</span><span><strong>{title}</strong><small>{detail}</small></span><span className="active-dot"><i /> Active</span><span className="levels"><i /><i /><i /><i /></span></div>; }
function PreviewLine({ time, source, children }: { time: string; source: string; children: React.ReactNode }) { return <div className="preview-line"><time>{time}</time><span><b className={source === 'YOU' ? 'you' : ''}>{source}</b><p>{children}</p></span></div>; }

function Intro() { return <section className="intro section-frame" id="features"><div className="section-kicker">MEETMIND</div><h2>From conversation<br />to clarity.</h2><p className="intro-copy">Important decisions and responsibilities often disappear once a meeting ends. MeetMind creates a structured record of what happened, what was decided and what needs to happen next.</p><div className="three-columns"><FeatureColumn number="01" title="CAPTURE">Capture authorized meeting audio and your microphone independently for more reliable transcription.</FeatureColumn><FeatureColumn number="02" title="UNDERSTAND">Generate structured transcripts, summaries, key points and decisions from meeting conversations.</FeatureColumn><FeatureColumn number="03" title="ACT">Review AI-detected action items and turn verified items into tasks with deadlines.</FeatureColumn></div></section>; }
function FeatureColumn({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <div className="feature-column"><span className="column-number">{number}</span><h3>{title}</h3><p>{children}</p></div>; }

function Workflow() { const steps = [{ n: '01', title: 'Start meeting', text: 'Confirm you are authorized to record.' }, { n: '02', title: 'Capture audio', text: 'Keep meeting and microphone streams separate.' }, { n: '03', title: 'Transcribe', text: 'Create a timestamped record of the conversation.' }, { n: '04', title: 'Generate insights', text: 'Surface summaries, points and decisions.' }, { n: '05', title: 'Review items', text: 'Confirm what should become a real task.' }, { n: '06', title: 'Track tasks', text: 'Keep deadlines visible after the call.' }]; return <section className="workflow section-frame" id="workflow"><div className="section-kicker">HOW IT WORKS</div><div className="workflow-heading"><h2>One meeting.<br /><em>A structured outcome.</em></h2><p>MeetMind follows the shape of a real meeting, from the first permission to the last verified responsibility.</p></div><div className="workflow-line">{steps.map((step, index) => <div className="workflow-step" key={step.n}><span className="step-number">{step.n}</span><span className="step-connector" />{index === 0 ? <Play className="step-icon" size={14} fill="currentColor" /> : index === 5 ? <Check className="step-icon" size={15} /> : <span className="step-dot" />}<h3>{step.title}</h3><p>{step.text}</p></div>)}</div></section>; }

function AudioFeature() { return <section className="feature-band section-frame"><div className="feature-copy"><div className="section-kicker">AUDIO CAPTURE</div><h2>Two audio sources.<br /><em>One accurate timeline.</em></h2><p>MeetMind captures browser meeting audio and your microphone independently rather than mixing them into a single recording.</p><div className="capture-rows"><div><span className="feature-icon"><Headphones size={16} /></span><span><b>MEETING AUDIO</b><small>Browser tab</small></span><strong><i /> Active</strong></div><div><span className="feature-icon"><Mic size={16} /></span><span><b>MICROPHONE</b><small>Your voice</small></span><strong><i /> Active</strong></div></div></div><div className="capture-diagram"><DiagramNode title="Meeting audio" detail="Browser tab" /><DiagramNode title="Microphone" detail="Your voice" /><div className="diagram-arrow"><ArrowDown size={14} /></div><div className="diagram-node accent-node"><AudioLines size={15} /><span><b>Timestamp alignment</b><small>Chronological merge</small></span></div><div className="diagram-arrow"><ArrowDown size={14} /></div><div className="diagram-node final-node"><FileText size={15} /><span><b>Structured transcript</b><small>Ready for analysis</small></span></div></div></section>; }
function DiagramNode({ title, detail }: { title: string; detail: string }) { return <div className="diagram-node"><span className="diagram-source"><i /></span><span><b>{title}</b><small>{detail} · independent transcription</small></span></div>; }

function Intelligence() { return <section className="intelligence section-frame"><div className="intelligence-copy"><div className="section-kicker">MEETING INTELLIGENCE</div><h2>More than<br /><em>a transcript.</em></h2><p>MeetMind organizes conversations into information you can actually use after the meeting.</p><div className="intel-list"><span><Check size={14} />Summaries that preserve the point</span><span><Check size={14} />Decisions separated from discussion</span><span><Check size={14} />Action items ready for review</span></div></div><div className="meeting-detail"><div className="detail-tabs"><span className="active">Overview</span><span>Transcript</span><span>Action items</span></div><div className="detail-document"><small>AI SUMMARY</small><p>“The team reviewed frontend progress and agreed to complete the dashboard before Friday. API integration will begin after the UI review.”</p><small>KEY POINTS</small><ul><li>Dashboard implementation due Friday.</li><li>API integration follows UI review.</li><li>Team review scheduled Monday.</li></ul><small>DECISIONS</small><div className="decision-line"><Check size={14} />React will be used for the frontend.</div><div className="decision-line"><Check size={14} />Audio sources remain independent during transcription.</div></div></div></section>; }

function HumanVerification() { return <section className="verification section-frame"><div className="verification-header"><div className="section-kicker">HUMAN VERIFICATION</div><h2>AI suggests.<br /><em>You decide.</em></h2><p>MeetMind treats AI-detected action items as suggestions until they are reviewed by a person.</p></div><div className="action-demo"><div className="action-demo-top"><span>ACTION ITEM / AI DETECTED</span><span>1 of 3</span></div><div className="action-row"><div className="action-title"><span className="action-check"><Circle size={14} /></span><span><b>Complete dashboard</b><small>Project Planning</small></span></div><div><small>ASSIGNEE</small><b>Riya</b></div><div><small>DUE</small><b>Oct 5</b></div><StatusDemo /></div><div className="action-buttons"><button className="confirm"><Check size={13} />Confirm</button><button>Edit</button><button className="reject">Reject</button></div><div className="verified-flow"><span>AI suggestion</span><ArrowRight size={13} /><strong>Verified task</strong><span className="verified-check"><Check size={11} /></span></div></div><p className="verification-note">AI can misunderstand conversations. MeetMind keeps people in control before suggested responsibilities become tracked tasks.</p></section>; }
function StatusDemo() { return <div><small>STATUS</small><span className="needs-review"><i /> Needs review</span></div>; }

function TasksPreview() { return <section className="tasks-section section-frame"><div className="section-kicker">TASK MANAGEMENT</div><div className="tasks-heading"><h2>Meetings shouldn't end<br /><em>with forgotten responsibilities.</em></h2><p>Keep commitments visible, connected to their source, and easy to finish.</p></div><div className="task-window"><div className="task-window-head"><span>TASKS</span><div><b>All</b><span>Pending</span><span>Completed</span><span>Overdue</span></div></div><div className="task-table-head"><span>Task</span><span>Source</span><span>Due</span><span>Status</span></div><TaskPreviewRow title="Complete dashboard" source="Project Planning" due="Today" status="Pending" /><TaskPreviewRow title="API integration" source="Backend Discussion" due="Tomorrow" status="Pending" /><TaskPreviewRow title="Review summary" source="Weekly Sync" due="Oct 6" status="Completed" /></div></section>; }
function TaskPreviewRow({ title, source, due, status }: { title: string; source: string; due: string; status: string }) { return <div className="task-table-row"><span><span className={`task-bullet ${status === 'Completed' ? 'done' : ''}`}>{status === 'Completed' && <Check size={10} />}</span><b>{title}</b></span><span>{source}</span><span>{due}</span><span className={status === 'Completed' ? 'task-complete' : 'task-pending'}><i />{status}</span></div>; }

function AnalyticsPreview() { return <section className="analytics-section section-frame"><div className="analytics-intro"><div className="section-kicker">ANALYTICS</div><h2>Understand where<br /><em>the work goes.</em></h2><p>Track meeting activity, task completion and overdue responsibilities across your workspace.</p></div><div className="analytics-preview"><div className="analytics-stats"><span><b>24</b><small>Meetings</small></span><span><b>18.5h</b><small>Meeting hours</small></span><span><b>56</b><small>Tasks generated</small></span><span><b>75%</b><small>Completion rate</small></span></div><div className="analytics-charts"><div className="activity-chart"><div className="chart-label">MEETING ACTIVITY <span>7D</span></div><div className="chart-bars">{[42, 55, 36, 74, 58, 86, 68].map((height, i) => <span key={i}><i style={{ height: `${height}%` }} /><small>{['M', 'T', 'W', 'T', 'F', 'S', 'S'][i]}</small></span>)}</div></div><div className="completion-chart"><div className="chart-label">TASK COMPLETION</div><div className="completion-body"><div className="chart-donut"><b>75%</b></div><div><span><i className="green" />Completed <b>42</b></span><span><i className="amber" />Pending <b>11</b></span><span><i className="red" />Overdue <b>3</b></span></div></div></div></div></div></section>; }

function Privacy() { return <section className="privacy-section section-frame"><div className="privacy-heading"><div className="section-kicker">PRIVACY</div><h2>Your conversations<br /><em>deserve careful handling.</em></h2><p>MeetMind is designed to minimize unnecessary audio retention. Raw audio can be removed after successful processing while structured meeting outputs remain available according to the application's retention settings.</p></div><div className="privacy-points"><PrivacyPoint title="AUTHORIZED CAPTURE">Recording begins only after the user confirms they have authorization to capture and process the meeting.</PrivacyPoint><PrivacyPoint title="MINIMAL AUDIO RETENTION">Raw audio is removed after successful processing according to configured retention rules.</PrivacyPoint><PrivacyPoint title="HUMAN CONTROL">AI-generated action items remain unverified until explicitly reviewed.</PrivacyPoint></div></section>; }
function PrivacyPoint({ title, children }: { title: string; children: React.ReactNode }) { return <div><ShieldCheck size={16} /><span><b>{title}</b><p>{children}</p></span></div>; }

function About() { return <section className="about-section section-frame" id="about"><div className="section-kicker">ABOUT</div><div className="about-grid"><h2>Building better outcomes<br /><em>from meetings.</em></h2><div><p>MeetMind was created to address a common problem in online collaboration: important discussions happen during meetings, but decisions, responsibilities and deadlines are often difficult to track afterward.</p><p>Our goal is to bridge the gap between meeting conversations and actionable outcomes through transcription, structured AI analysis, human verification and task management.</p></div></div></section>; }

function Contact() { const [sent, setSent] = useState(false); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); }; return <section className="contact-section section-frame" id="contact"><div className="contact-copy"><div className="section-kicker">CONTACT</div><h2>Have a<br /><em>question?</em></h2><p>Get in touch about MeetMind, the project, or technical implementation.</p></div><form className="contact-form" onSubmit={submit}><label>Name<input required placeholder="Your name" /></label><label>Email<input required type="email" placeholder="you@example.com" /></label><label>Subject<input required placeholder="How can we help?" /></label><label>Message<textarea required placeholder="Write your message..." /></label><button className="primary-button" type="submit">{sent ? <><Check size={15} /> Message sent</> : <>Send message <ArrowRight size={15} /></>}</button></form></section>; }

function FinalCta({ goTo }: { goTo: (route: Route) => void }) { return <section className="final-cta section-frame"><div className="final-rule" /><div className="section-kicker">START WITH THE NEXT CONVERSATION</div><h2>Make the next meeting<br /><em>easier to act on.</em></h2><p>Capture the discussion. Understand what matters. Keep track of what comes next.</p><div><button className="primary-button" onClick={() => goTo('/register')}>Get started <ArrowRight size={15} /></button><button className="quiet-button" onClick={() => goTo('/login')}>Sign in</button></div></section>; }
function Footer({ goTo }: { goTo: (route: Route) => void }) { return <footer className="site-footer section-frame"><div className="footer-top"><div><button className="logo-button" onClick={() => scrollToSection('top')}><Logo /></button><p>AI-Powered Meeting Assistant</p></div><div className="footer-links"><div><b>Product</b><button onClick={() => scrollToSection('product')}>Product preview</button><button onClick={() => scrollToSection('features')}>Features</button><button onClick={() => scrollToSection('workflow')}>How it works</button></div><div><b>Company</b><button onClick={() => scrollToSection('about')}>About</button><button onClick={() => scrollToSection('contact')}>Contact</button><button onClick={() => scrollToSection('contact')}>Privacy</button></div></div></div><div className="footer-bottom"><span>© 2026 MeetMind</span><span>Academic Project</span></div></footer>; }

function AuthPage({ type, goTo }: { type: 'login' | 'register'; goTo: (route: Route) => void }) { const register = type === 'register'; return <div className="auth-page"><div className="auth-top"><button className="logo-button" onClick={() => goTo('/')}><Logo /></button><button className="quiet-button" onClick={() => goTo('/')}>Back to homepage <ArrowRight size={14} /></button></div><div className="auth-panel"><div className="auth-mark"><Logo /></div><div className="section-kicker">MEETMIND WORKSPACE</div><h1>{register ? 'Create your workspace.' : 'Welcome back.'}</h1><p>{register ? 'Start turning conversations into outcomes.' : 'Sign in to continue to MeetMind.'}</p><form onSubmit={(event) => event.preventDefault()}><label>{register && 'Full name'}{register && <input required placeholder="Riya Mehta" />}Email<input required type="email" placeholder="you@example.com" /></label><label>Password<input required type="password" placeholder="••••••••" /></label>{register && <label>Confirm password<input required type="password" placeholder="••••••••" /></label>}<button className="primary-button" type="submit">{register ? 'Create account' : 'Continue'} <ArrowRight size={15} /></button></form><div className="auth-switch">{register ? 'Already have an account?' : 'Don’t have an account?'} <button onClick={() => goTo(register ? '/login' : '/register')}>{register ? 'Sign in' : 'Get started'}</button></div><small className="auth-legal">By continuing, you agree to use MeetMind only for meetings you are authorized to capture.</small></div></div>; }

export default App;
